apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rom-example
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rom-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-rom-pvc
  template:
    metadata:
      labels:
        app: app-rom-pvc
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-rom-example
