apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rwo-example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rwo-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-rwo-pvc
  template:
    metadata:
      labels:
        app: app-rwo-pvc
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-rwo-example