apiVersion: v1
kind: Pod
metadata:
  name: ssd-node-selector-pod
spec:
  containers:
    - name: nginx
      image: nginx
  nodeSelector:
    disktype: ssd
---
apiVersion: v1
kind: Pod
metadata:
  name: ssd-node-name-pod
spec:
  containers:
    - name: nginx
      image: nginx
  nodeName: k3s-worker-1
