apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-delete-rwm
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /tmp/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-delete-rwm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-delete-rwm
spec:
  replicas: 2  # ReadWriteMany allows multiple pods to write
  selector:
    matchLabels:
      app: nginx-delete-rwm
  template:
    metadata:
      labels:
        app: nginx-delete-rwm
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: data-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-delete-rwm