apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-emptydir
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-emptydir
  template:
    metadata:
      labels:
        app: app-emptydir
    spec:
      containers:
      - name: app
        image: alpine:latest
        command: ['sh', '-c', 'while true; do echo "logging" >> /cache/logs.txt; sleep 1; done']
        volumeMounts:
          - name: cache-volume
            mountPath: /cache
      - name: log
        image: alpine:latest
        command: ['sh', '-c', 'tail -F /cache/logs.txt']
        volumeMounts:
          - name: cache-volume
            mountPath: /cache
      volumes:
      - name: cache-volume
        emptyDir: {}