apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hostpath
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-hostpath
  template:
    metadata:
      labels:
        app: app-hostpath
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
      volumes:
      - name: log-volume
        hostPath:
          path: /var/log/nginx
          type: DirectoryOrCreate