apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-recycle-rom
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-path
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-recycle-rom
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-recycle-rom
spec:
  replicas: 2  # ReadOnlyMany allows multiple pods to read
  selector:
    matchLabels:
      app: nginx-recycle-rom
  template:
    metadata:
      labels:
        app: nginx-recycle-rom
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: data-volume
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-recycle-rom