apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retain-rwo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-retain-rwo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-retain-rwo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-retain-rwo
  template:
    metadata:
      labels:
        app: nginx-retain-rwo
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: data-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-retain-rwo