apiVersion: v1
kind: Pod
metadata:
  name: nginx-probe-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

    # Startup probe
    startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 30 # check 30 times
      periodSeconds: 10 # every 10 seconds -> 5 Minutes

    # Liveness probe
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15 # start 15 seconds after the container starts OR startup probe succeeds
      periodSeconds: 20
      timeoutSeconds: 5 # fail after 5 seconds without an answer
      failureThreshold: 3 # restart container after 3 fails

    # Readiness probe
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1 # if it succeeds once, the container is considered ready